---
title: "Chihara & Hesterberg Outline"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    highlight: textmate
    theme: cosmo
---

<hr>

### Introduction to R

     DataCamp: Introduction to R
     DataCamp: Reporting with R Markdown
     DataCamp: Working with the R Studio IDE (Part 1)/Orientation



### Introduction to Probability

     DataCamp: Foundations of Probability in R

P.1. Basic Probability

P.2. Combinatorics

P.3. Random Variables

1. Video: [An Introduction to Discrete Random Variables](https://youtu.be/oHcrna8Fk18)
2. Video: [An Introduction to Continuous Probability Distributions](https://youtu.be/OWSOhpS00_s)
3. Video: [Finding Probabilities and Percentiles for a Continuous Probability Distribution](https://youtu.be/EPm7FdajBvc)
4. Video: [The Expected Value and Variance of Discrete Random Variables](https://youtu.be/Vyk8HQOckIE)
5. Video: [Deriving the Mean and Variance of a Continuous Probability Distribution](https://youtu.be/Ro7dayHU5DQ)

P.4. Binomial Distribution

1. Video: [Introduction to the Bernoulli Distribution](https://youtu.be/bT1p5tJwn_0)
2. Video: [The Bernoulli Distribution: Deriving the Mean and Variance](https://youtu.be/bC6WIpRgMuc)
3. Video: [An Introduction to the Binomial Distribution](https://youtu.be/qIzC1-9PwQo)
4. Video: [Binomial/Not Binomial: Some Examples](https://youtu.be/UJFIZY0xx_s)
5. Video: [The Binomial Distribution: Mathematically Deriving the Mean and Variance](https://youtu.be/8fqkQRjcR1M)
* Zener Card Case Study

P.5. Normal Distribution

1. Video: [An Introduction to the Normal Distribution](https://youtu.be/iYiOVISWXS4)
2. Video: [Standardizing Normally Distributed Random Variables](https://youtu.be/4R8xm19DmPM)
3. Video: [An Introduction to the Chi-Square Distribution](https://youtu.be/hcDb12fsbBU)
4. Video: [An Introduction to the t Distribution](https://youtu.be/T0xRanwAIiI)

P.6. Other Distributions

1. Video: [Introduction to the Continuous Uniform Distribution](https://youtu.be/izE1dXrH5JA)
* Exponential Distribution



### Chapter 1 -- Data and Case Studies

     DataCamp: Introduction to Data

1.1. Case Study: Flight Delays

1.2. Case Study: Birth Weights of Babies

1.3. Case Study: Verizon Repair Times

1.4. Sampling

1.5. Parameters and Statistics

1.6. Case Study: General Social Survey

1.7. Sample Surveys

1.8. Case Study: Beer and Hot Wings

1.9. Case Study: Black Spruce Seedlings

1.10. Studies

1.11. Exercises



### Chapter 2 -- Exploratory Data Anlaysis

     DataCamp: Intro to Statistics with R: Introduction
     DataCamp: Data Manipulation in R with dplyr
     DataCamp: Data Visualization with ggplot2 (Part 1)
     DataCamp: Exploratory Data Analysis

2.1. Basic Plots

2.2. Numeric Summaries

2.2.1. Center

2.2.2. Spread

2.2.3. Shape

2.3. Boxplots

2.4. Quantiles and Normal Quantile Plots

1. Video: [Normal Quantile-Quantile Plots](https://youtu.be/X9_ISJ0YpGw)

2.5. Empirical Cumulative Distribution Plots

2.6. Scatter Plots

2.7. Skewness and Kurtosis

2.8. Exercises



### Chapter 3 -- Hypothesis Testing

     DataCamp: Intro to Statistics with R: Student's T-Test

3.1. Introduction to Hypothesis Testing

1. Video: [An Introduction to Hypothesis Testing](https://youtu.be/tTeMYuS87oU)
2. Video: [What is a p-value?](https://youtu.be/UsU-O2Z1rAs)
3. Video: [Type I Errors, Type II Errors, and the Power of the Test](https://youtu.be/7mE-K_w1v90)
4. Video: [Statistical Significance versus Practical Significance](https://youtu.be/_k1MQTUCXmU)

3.2. Hypotheses

3.3. Permutation Tests

1. Video: [Inference for Two Means: Introduction](https://youtu.be/86ss6qOTfts)
2. Video: [The Sampling Distribution of the Difference in Sample Means](https://youtu.be/4HB-FL529ag)

3.3.1. Implementation Issues
 
3.3.2. One-Sided and Two-Sided Tests

3.3.3. Other Statistics

1. Video: [An Introduction to Inference for Two Proportions](https://youtu.be/g0at6LpYvHc)
2. Video: [Inference for Two Proportions: An Example](https://youtu.be/OIYkOiQX3fk)

3.3.4. Assumptions

3.4. Contingency Tables

3.4.1. Permutation Test for Independence

3.4.2. Chi-Square Reference Distribution

3.5. Chi-Square Test of Independence

1. Video: [Chi-square Tests for Two-way Tables](https://youtu.be/L1QPBGoDmT0)

3.6. Test of Homogeneity

3.7. Goodness-of-Fit: All Parameters Known

1. Video: [Chi-square Tests for One-way Tables](https://youtu.be/gkgyg-eR0TQ)
2. Video: [Chi-square Goodness of Fit Test for the Binomial Distribution](https://youtu.be/O7wy6iBFdE8)

3.8. Goodness-of-Fit: Some Parameters Estimated 

3.9. Exercises 



### Chapter 4 -- Sampling Distributions

4.1. Sampling Distributions

1. Video: [Sampling Distributions: Introduction to the Concept](https://youtu.be/Zbw-YvELsaM)

4.2. Calculating Sampling Distributions

4.3. The Central Limit Theorem

1. Video: [The Sampling Distribution of the Sample Mean](https://youtu.be/q50GpTdFYyI)
2. Video: [Introduction to the Central Limit Theorem](https://youtu.be/Pujol1yC1_A)
3. Video: [Deriving the Mean and Variance of the Sample Mean](https://youtu.be/7mYDHbrLEQo)
4. Video: [Proof that the Sample Variance is an Unbiased Estimator of the Population Variance](https://youtu.be/D1hgiAla3KI)

4.3.1. CLT for Binomial Data

1. Video: [The Normal Approximation to the Binomial Distribution](https://youtu.be/CCqWkJ_pqNU)

4.3.2. Continuity Correction for Discrete Random Variables

4.3.3. Accuracy of the Central Limit Theorem

4.3.4. CLT for Sampling Without Replacement

4.4. Exercises



### Chapter 5 -- The Bootstrap

5.1. Introduction to the Bootstrap

5.2. The Plug-In Principle

5.2.1. Estimating the Population Distribution

5.2.2. How Useful is the Bootstrap Distribution?

5.3. Bootstrap Percentile Intervals

5.4. Two Sample Bootstrap

5.4.1 The Two Independent Populations Assumption

5.5. Other Statistics

5.6. Bias

5.7. Monte Carlo Sampling: "The Second Bootstrap Principle"

5.8. Accuracy of Bootstrap Distributions

5.8.1. The Sample Mean: Large Sample Size

5.8.2. The Sample Mean: Small Sample Size

5.8.3. Sample Median

5.9. How Many Bootstrap Samples Are Needed?

5.10. Exercises



### Supplemental Materials.

* [JBstatistics](http://www.jbstatistics.com/)

