---
title: "STT 3850 Statistical Data Analysis 1 --- Course Schedule"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    highlight: textmate
    theme: cosmo
    css: "../css/style.css"
---

<hr>

```{block, note-text, type='rmdnote'}
* The textbook is available via the rental system.
* Please bring a notebook and pencil to every class.
* Be prepared to actively participate and collaborate.
* Access all of the DataCamp assignments via [AsULearn](https://AsULearnappstate.edu)
* We meet TUE/THU 12:30 to 01:45pm and WED 01:00-1:50pm.
* **This schedule is a work in progress. Check often for updates!**
* **Assignments are due @11:00pm on the Friday of the week they are assigned, unless otherwise indicated.**
```

Class time in this course will be a mix of lecture and hands-on activities. STT 3850 is an introductory course with no statistics prerequisite and is required for students from several majors, who come into the course with a broad mix of mathematics, statistics, and programming skills. This means that the most effective mode of instruction is a flipped classroom approach where traditional lecture occurs outside the classroom while class time is spent in collaborative work where students can give and receive individualized help from peers and the instructor. Do not treat this instructional style as an invitation to skip class. You classmates are one of your greatest resources.

## Week 10 (Mar 26) {-}

  In Class Tuesday: 
  
  * Permutation tests for means
  * Traditional t-tests for means
  
  Additional resources for hypothesis tests:

  * Watch [An Introduction to Hypothesis Testing](https://youtu.be/tTeMYuS87oU)
  * Watch [What is a *p*-value?](https://youtu.be/UsU-O2Z1rAs)
  * Watch [Type I Errors, Type II Errors, and Power](https://youtu.be/7mE-K_w1v90) 
  * Watch [Statistical Significance versus Practical Significance](https://youtu.be/_k1MQTUCXmU)  
  * Watch [Inference for Two Means: Introduction](https://youtu.be/86ss6qOTfts)
  * Watch [Sampling Distribution of the Difference in Sample Means](https://youtu.be/4HB-FL529ag)
  * Watch [Welch (Unpooled Variance) t Tests and Confidence Intervals: Introduction](https://youtu.be/2-ecXltt2vI)
  * Watch [Welch (Unpooled Variance) t Tests and Confidence Intervals: An Example](https://youtu.be/gzrmHpA54Sc)
  
  Before Wednesday's Class:
  
  * Read Chihara Sections 3.3.3 and 3.3.4

  * Watch [An Introduction to Inference for Two Proportions](https://youtu.be/g0at6LpYvHc)
  * Watch [Inference for Two Proportions: An Example](https://youtu.be/OIYkOiQX3fk)
  
  In Class Wednesday:
  
  * Permutation tests for proportions
  
  Before Thursday's Class:
  
  * Read Chihara Sections 3.4, 3.5, 3.6
  * Watch [An Introduction to the Chi-Square Distribution](https://youtu.be/hcDb12fsbBU)
  * Watch [Chi-Square Tests of Independence](https://youtu.be/L1QPBGoDmT0)
  
  In Class Thursday:
  
  * Permutation test for independence
  * Chi-square test of independence
  * Test of homogeneity

  Before Next Wednesday's Class
  
  * Read Chihara Sections 3.4, 3.5, 3.6


## Week 11 (April 02; No Classes April 02/03) {-}

  In Class Wednesday:
  
  * Permutation test for independence
  * Chi-square test of independence
  * Test of homogeneity
  
  Before Thursday's Class:
  
  * Review Chihara Chapter 3
  
  In Class Thursday:
  
  * Hypothesis testing problem session
  
  Before Next Tuesday's Class
  
  * Read Chihara Section 4.1
  * Watch [Sampling Distributions: Introduction to the Concept](https://youtu.be/Zbw-YvELsaM)
  * Watch [The Expected Value and Variance of Discrete Random Variables](https://youtu.be/Vyk8HQOckIE)
  * Watch [Deriving the Mean and Variance of a Continuous Probability Distribution](https://youtu.be/Ro7dayHU5DQ)
  * Optional: [Khan Academy Sampling Distributions Library](https://www.khanacademy.org/math/statistics-probability/sampling-distributions-library) 


## Week 12 (Apr 09) {-}

  In Class Tuesday: 
  
  * Sampling distributions

  Before Wednesday's Class:
  
  * Read Chihara Section 4.2
  
  In Class Wednesday:
  
  * Sampling distributions
  
  Before Thursday's Class:
  
  * Read Chihara Section 4.3
  * Watch [Introduction to the Central Limit Theorem](https://youtu.be/Pujol1yC1_A)
  * Watch [Deriving the Mean and Variance of the Sample Mean](https://youtu.be/7mYDHbrLEQo)
  * Watch [The Normal Approximation to the Binomial Distribution](https://youtu.be/CCqWkJ_pqNU) 
  
  In Class Thursday:
  
  * Central limit theorem
  * Continuity correction

  Before Next Tuesday's Class
  
  * Read Chihara Section 5.1
  * Watch [Bootstrap Confidence Intervals using Percentiles](https://youtu.be/GbptZEBuOj4)


## Week 13 (Apr 16) {-}

  In Class Tuesday: 
  
  * Introduction to bootstrapping

  Before Wednesday's Class:
  
  * Read Chihara Section 5.2
  
  In Class Wednesday:
  
  * Plug-in principle
  
  Before Thursday's Class:
  
  * Read Chihara Section 5.3
  
  In Class Thursday:
  
  * Bootstrap percentie intervals

  Before Next Wednesday's Class
  
  * Review Chihara Chapter 4


## Week 14 (Apr 23) {-}

  In Class Tuesday: 
  
  * Sampling distribution problem session

  Before Wednesday's Class:
  
  * Review Chihara Chapter 5
  
  In Class Wednesday:
  
  * Bootstrapping problem session
  
  Before Thursday's Class:
  
  * Review Chihara Chapters 3, 4, and 5
  
  In Class Thursday:
  
  * Exam 2

  Before Next Tuesdays's Class
  
  * Complete Exam 2


## Week 15 (April 30; May 03 is Reading Day) {-}

* In Class: TBA
* Additional material TBA


### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  Our [final exam time](https://registrar.appstate.edu/sites/registrar.appstate.edu/files/asu_spring_2018_exam_schedule.pdf) is Thursday, May 10 @ 11:00am.
```
