---
title: "STT 3850 Statistical Data Analysis 1<br>Summer 2018 Course Schedule"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
    highlight: textmate
    theme: cosmo
    css: "../css/style.css"
---

<hr>

```{block, start-note, type='rmdnote'}
* We will use rental and free digital textbooks.
* All required software for this course is provided.
* Please bring a notebook and pencil to every class.
* Be prepared to actively participate and collaborate.
* Refer to the [Course Syllabus](../Syllabus/SyllabusF2018.html) for additional details.
* **This schedule is a work in progress. Check often for updates!**
```

Class time in this course will be a mix of lecture and hands-on activities. STT 3850 is an introductory course with no statistics prerequisite and is required for students from several majors. Students come into the course with a broad mix of mathematics, statistics, and programming skills. This means that the most effective mode of instruction tends to be a semi-flipped classroom approach where some lecture occurs outside the classroom in the form of videos. This frees up class time to spend on collaborative work where students can give and receive individual help from peers and the instructor. Do not treat this instructional mode as an invitation to skip class! Your classmates are one of your greatest resources.


## Day 01 (TUE May 29)

   In Class:
   
   * Overview, syllabus, class assessments
   * Introduction to R and R Studio server
   * Vietnam draft activity and discussion

   Before Next Class: 
   
   * Complete AsULearn Lesson *The Development of R*
   * Complete DataCamp *Introduction to R*
   * Complete DataCamp *Working with the RStudio IDE (Part 1)/Orientation*


## Day 02 (WED May 30)

   In Class:

   * Vectors and matrices
   * Reading in `csv` files
   * Structure of datasets
   * Addressing variables
   * <strike>`filter` and `group_by`</strike>
   * <strike>`table` and `summarize`</strike>
   * Dataset structure activity

   Before Next Class: 
   
   * Read Chihara and Hesterberg Chapter 1
   * Complete DataCamp *Introduction to Data* 
   * Complete DataCamp *Reporting with R Markdown* 

```{block, day02-note, type='rmdnote'}
* REMINDER: You should be taking notes on concepts, functions, and procedures presented in the DataCamp modules. Markdown documents are a good way to create your own annotated code library and to integrate information from various sources (e.g., textbook readings, videos, class exercises). Take time to organize your notes!
```

## Day 03 (THU May 31)

   In Class:

   * From yesterday
      + <strike>`filter` and `group_by`</strike>
      + `table` <strike>and `summarize`</strike>
      * Variables types
      + categorical
      + numerical
   * Exploratory Data Analysis (EDA)
      + shape
      + center
      + spread
      + outliers
   * Data visualization
      + <strike>barplots</strike>
      + histograms
      + <strike>density plots</strike>
      + <strike>scatterplots</strike>
      + <strike>time series plots</strike>

   Before Next Class: 
   
   * Read Chihara and Hesterberg Sections 2.1, 2.2, and 2.6
   * Complete DataCamp *Introduction to Statistics with R: Introduction* 

## Day 04 (FRI Jun 01)

   In Class:

   * From earlier
      + `filter` and `group_by`
      + `table` and `summarize`
   * Data visualization
      + <strike>barplots</strike>
      + histograms
      + density plots
      + <strike>scatterplots</strike>
      + <strike>time series plots</strike>
   * Data summaries
      + tables
      + statistics
      
   Before Next Class: 
   
   * Read Chihara and Hesterberg Section 2.3
   * Complete DataCamp *Data Manipulation with R in `dplyr`*
   
```{block, day04-note, type='rmdnote'}
* This has been a busy week! If you're behind on the first few assignments, get caught up before Monday. The data summary and visualization skills you learn in the early part of the course will be used throughout the remaining weeks.
```

## Day 05 (MON Jun 04)

   In Class:
   
   * From Friday
      + barplot
      + scatterplots
      + time series plots
   * Data Summaries
      + <strike>tables</strike>
      + <strike>statistics</strike>
   * Boxplots
   * Outliers
      
   Before Next Class: 

   * Complete DataCamp *Data Visualization with `ggplot`*

## Day 06 (TUE Jun 05)

   In Class:
   
   * Putting it all together!
   
   Before Next Class: 
   
   * Complete AsULearn Lesson *Discrete and Continuous Random Variables*
   * Complete AsULearn Lesson *Binomial Distribution*

## Day 07 (WED Jun 06)

   In Class:
   
   * Basic Probability
   * Bernoulli Trials
   * Binomial Distribution 

   Before Next Class: 
   
   * Read Chihara and Hesterberg Sections 2.4, 2.5, and 2.7
   * Complete AsULearn Lesson *Normal Distribution*
   
## Day 08 (THU Jun 07)

   In Class:
   
   * Normal distribution
   * Assessing normality
      + skewness
      + kurtosis
      + QQ plots
      + ECDF plots

   Before Next Class: 
   
   * Read Chihara and Hesterberg Section 2.7
   * Complete DataCamp *Exploratory Data Analysis*

## Day 09 (FRI Jun 08)

   In Class:

   * Normal approximation
   * Continuity correction
   * Other continuous RVs

   Before Next Class: 
   
   * Complete DataCamp *Foundations of Probability*
   
```{block, day09-note, type='rmdnote'}
* Congratulations, you've reached the end of Week 2! Use the weekend to finish up your work and organize your notes. Monday we'll review the material we've covered in preparation for Exam 1 on Tuesday. Please come to class with some questions you'd like answered.
```

## Day 10 (MON Jun 11)
 
   In Class:
   
   * Putting it all together!

   Before Next Class: 
   
   * Prepare for EXAM 1

## Day 11 (TUE Jun 12)

   In Class:
   
   * EXAM 1

   Before Next Class: 
   
   * Read Chihara and Hesterberg Sections 3.1 -- 3.3
   * Complete AsULearn Lesson *Theory and Concepts of Hypothesis Testing*

## More TBA!

```{block, FINAL, type='rmdnote'}
*  I will add to this schedule as we progress through the course. Future topics include hypothesis testing (Chapter 3), sampling distributions (Chapter 4), and bootstrapping (Chapter 5).
```
