---
title: "STT 3850 Statistical Data Analysis 1<br>Fall 2018 Course Schedule"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
    highlight: textmate
    theme: cosmo
    css: "../css/style.css"
---

<hr>

```{block, start-note, type='rmdnote'}
* We will use rental and free digital textbooks.
* All required software for this course is provided.
* Please bring a notebook and pencil to every class.
* Be prepared to actively participate and collaborate.
* Refer to the [Course Syllabus](../Syllabus/SyllabusF2018.html) for additional details.
* **This schedule is a work in progress. Check often for updates!**
```

Class time in this course will be a mix of lecture and hands-on activities. STT 3850 is an introductory course with no statistics prerequisite and is required for students from several majors. Students come into the course with a broad mix of mathematics, statistics, and programming skills. This means that the most effective mode of instruction tends to be a semi-flipped classroom approach where some lecture occurs outside the classroom in the form of videos. This frees up class time to spend on collaborative work where students can give and receive individual help from peers and the instructor. Do not treat this instructional mode as an invitation to skip class! Your classmates are one of your greatest resources.

## Week 01 (AUG 20)

IN CLASS

   * NO CLASS MONDAY (Convocation)
   * Overview, syllabus, class assessments
   * Introduction to R and RStudio server

ASSIGNMENTS

   * Read Chihara and Hesterberg Chapter 1
   * Read _Modern Dive_, [Chapter 1. Introduction](https://moderndive.com/index.html)
   * Read [_Getting used to R, RStudio, and R Markdown_](https://ismayc.github.io/rbasics-book/)
   * Watch ["The History of S and R"](https://youtu.be/jk9S3RTAl38) (~10 minutes)
   * Watch ["Introduction to the R Language"](https://youtu.be/APm4SxJx0eg) (~30 minutes)
   * Complete _Introduction to R_ on [DataCamp](https://www.datacamp.com/)
   * Complete [A Tutorial on Loops in R - Usage and Alternatives](https://www.datacamp.com/community/tutorials/tutorial-on-loops-in-r)


## Week 02 (AUG 27)

IN CLASS

   * Creating and manipulating vectors
   * Dataset and variable vocabulary
   * Loading CSV files from the web
   * Creating and Manipulating Vectors activity (THU)
   
ASSIGNMENTS

   * Read Chihara and Hesterberg Section 2.1
   * Read _Modern Dive_, [Chapter 2. Getting Started with Data in R](https://moderndive.com/2-getting-started.html)
   * Read _Modern Dive_, [Chapter 3. Data Visualization via `ggplot2`](https://moderndive.com/3-viz.html)
   * Complete Video Lesson _Discrete and Continuous Random Variables_
   * Complete _Introduction to Data_ on [DataCamp](https://www.datacamp.com/)
   * Complete _Reporting with R Markdown_ on [DataCamp](https://www.datacamp.com/)
   * Complete Creating and Manipulating Vectors activity 
   
```{block, week2note, type='rmdnote'}
* REMINDER: You should be taking notes on concepts, functions, and procedures presented in the [DataCamp](https://www.datacamp.com/) modules. Markdown documents are a good way to create your own annotated code library and to integrate information from various sources (e.g., textbook readings, videos, class exercises). Take time to organize your notes!
```


## Week 03 (SEP 03)

IN CLASS

   * NO CLASS MONDAY (Labor Day)
   * Concepts of `tidy` data
   * Summarizing data
   * Summarizing Categorical Data activity
   
ASSIGNMENTS

   * Read Chihara and Hesterberg Sections 2.2 and 2.3
   * Read _Modern Dive_, [Chapter 4. Tidy Data via `tidyr`](https://moderndive.com/4-tidy.html)
   * Read _Modern Dive_, [Chapter 5. Data Wrangling via `dplyr`](https://moderndive.com/5-wrangling.html)
   * Complete Video Lesson _Measures of Center and Spread (Variability)_
   * Complete _Introduction to the Tidyverse_ on [DataCamp](https://www.datacamp.com/)
   * Complete Summarizing Categorical Data activity 

## Week 04 (SEP 10)

IN CLASS

   * Concepts of `tidy` data
   * Summarizing data
   * NO CLASS THURSDAY (Hurricane Florence)
   
ASSIGNMENTS

   * Read Chihara and Hesterberg Sections 2.2 and 2.3
   * Read _Modern Dive_, [Chapter 4. Tidy Data via `tidyr`](https://moderndive.com/4-tidy.html)
   * Read _Modern Dive_, [Chapter 5. Data Wrangling via `dplyr`](https://moderndive.com/5-wrangling.html)
   * Complete Video Lesson _Measures of Center and Spread (Variability)_


## Week 05 (SEP 17)

IN CLASS

   * NO CLASS MONDAY (Hurricane Florence)
   * NO CLASS TUESDAY (Hurricane Florence)
   * Summarizing Quantitative Data activity
   
ASSIGNMENTS
 
   * Complete _Exploratory Data Analysis_ on [DataCamp](https://www.datacamp.com/)
   * Complete Summarizing Quantitative Data activities 


## Week 06 (SEP 24)

IN CLASS

   * Fundamentals of probability
   * Binomial distribution
   * Normal distribution
   * Assessing normality

ASSIGNMENTS

   * Read Chihara and Hesterberg Sections 2.4, 2.5, 2.6, and 2.7
   * Complete Video Lesson _Binomial and Geometric Distributions_
   * Complete Video Lesson _Normal and Related Distributions_
   * Complete _Communicating with Data in the Tidyverse_ on [DataCamp](https://www.datacamp.com/)

```{block, week6note, type='rmdnote'}
* Make sure you are caught up on all assignments by the end of this week! Next week you will be putting everything you've learned to use in your group projects.
```


## Week 07 (OCT 01)  

IN CLASS

   * Group projects work time
   
ASSIGNMENTS

   * Complete group projects
   
   
## Week 08 (OCT 08)  

IN CLASS

   * Normal distribution
   * Assessing normality
   * Fundamentals of Hypothesis Testing
   * NO CLASS THURSDAY (Fall Break)

ASSIGNMENTS

   * Read Chihara and Hesterberg Sections 2.4, 2.5, 2.6, 2.7, 3.1, and 3.2
   * Complete Video Lesson _Normal and Related Distributions_
   * Complete Video Lesson _Theory and Concepts of Hypothesis Testing_
   * Complete _Foundations of Probability in R_ on [DataCamp](https://www.datacamp.com/)
   
   
## Week 09 (OCT 15)

IN CLASS

   * Tests for two means, two proportions
   
ASSIGNMENTS

   * Complete Video Lesson _Classical Hypothesis Testing for One Mean_
   * Complete Video Lesson _Classical Hypothesis Testing for Two Means_
   * Complete Video Lesson _Classical Hypothesis Testing for Proportions_


## Week 10 (OCT 22)

IN CLASS

   * Tests for two proportions, independence
   
ASSIGNMENTS

   * Complete Video Lesson _Chi-Square Tests for Tables of Counts_
   * Complete Hypothesis Testing: Comparing Two Groups activity
   

## Week 11 (OCT 29)

IN CLASS

   * DataCamp worktime (Monday)
   * Goodness of fit and homogeneity tests

ASSIGNMENTS

   * Work on _Foundations of Inference_ on [DataCamp](https://www.datacamp.com/)


## Week 12 (NOV 05)

IN CLASS

   * Sampling distributions
   * Normal approximation to the binomial

ASSIGNMENTS

   * Complete Video Lesson _Introduction to Sampling Distributions_
   * Complete _Foundations of Inference_ on [DataCamp](https://www.datacamp.com/)
   * Complete _Inference for Numerical Data_ on [DataCamp](https://www.datacamp.com/)
   * Complete Hypothesis Testing: Chi-Square tests activity


## Week 13 (NOV 12)

IN CLASS

   * Group projects work time
   
ASSIGNMENTS

   * Complete group projects
   

## Week 14 (NOV 19)

IN CLASS

   * Estimation
   * NO CLASS WEDNESDAY (Thanksgiving)
   * NO CLASS THURSDAY (Thanksgiving)

ASSIGNMENTS

   * TBA
   

## Week 15 (NOV 28)

IN CLASS

   * Estimation

ASSIGNMENTS

   * Complete _Inference for Categorical Data_ on [DataCamp](https://www.datacamp.com/)
   * Complete Estimation activity
   

## Week 16 (DEC 03)

IN CLASS

   * Group projects work time
   * NO CLASS THURSDAY (Reading Day)

ASSIGNMENTS

   * Complete group projects and presentations  
   
   
<hr>

__This schedule will be updated as the semester progresses!__

<hr>


### Final Exam

```{block, FINAL, type='rmdnote'}
You will be doing group project presentations during our [final exam](https://registrar.appstate.edu/sites/registrar.appstate.edu/files/asu_fall_2018_exam_schedule_final.pdf) period.

* Tuesday 12/11 @ 11am in WA307 for STT3850-102 (11am section)
* Wednesday 12/12 @ 8am in WA307 for STT3850-101 (10am section)
```
