---
title: "STT 3850 Statistical Data Analysis 1<br>Summer 2018 Course Schedule"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
    highlight: textmate
    theme: cosmo
    css: "../css/style.css"
---

<hr>

```{block, start-note, type='rmdnote'}
* The textbook is available via the rental system.
* Please bring a notebook and pencil to every class.
* Be prepared to actively participate and collaborate.
* We meet Monday -- Friday 10:20am to 12:30pm in WA303.
* **This schedule is a work in progress. Check often for updates!**
```

Class time in this course will be a mix of lecture and hands-on activities. STT 3850 is an introductory course with no statistics prerequisite and is required for students from several majors. Students come into the course with a broad mix of mathematics, statistics, and programming skills. This means that the most effective mode of instruction tends to be a semi-flipped classroom approach where some lecture occurs outside the classroom in the form of videos. This frees up class time to spend on collaborative work where students can give and receive individual help from peers and the instructor. Do not treat this instructional mode as an invitation to skip class! Your classmates are one of your greatest resources.


## Day 12 (WED Jun 13)

   In Class
   
   * No face-to-face meeting today

   Before Next Class: 
   
   * Read Chihara and Hesterberg Sections 3.1 -- 3.3 and 8.1
   * Complete AsULearn Lesson *Theory and Concepts of Hypothesis Testing*
   * Complete DataCamp *Intro to Statistics with R: Student's T-test*

## Day 13 (THU Jun 14)

   In Class:
   
   * Concept of hypothesis tests
   * Permutation tests for two means
   * Traditional tests for two means
   * One-tailed versus two-tailed significance

   Before Next Class:

   * Read *Chihara and Hesterberg* Sections 3.4 -- 3.5 and 8.2 -- 8.3
   * Complete AsULearn Lesson *Classical Hypothesis Testing for One Mean*

## Day 14 (FRI Jun 15)

   In Class:
   
   * Testing for two proportions   
   * Contingency/frequency tables
      + independence
      + homogeneity
      + goodness of fit
   
   Before Next Class: 
   
   * Read *Chihara and Hesterberg* Sections 3.6 -- 3.8
   * Complete AsULearn Lesson *TBA*

## Day 15 (MON Jun 18)
 
   In Class:
   
   * Contingency/frequency tables
      + independence
      + homogeneity
      + goodness of fit

   Before Next Class: 
   
   * Review *Chihara and Hesterberg* Chapter 3
   * Complete AsULearn Lesson *TBA*

## Day 16 (TUE Jun 19)

   In Class:
   
   * Putting it all together!

   Before Next Class: 
   
   * Prepare for EXAM 2

## Day 17 (WED Jun 20)

   In Class:
   
   * EXAM 2

   Before Next Class: 
   
   * Read *Chihara and Hesterberg* Sections 5.1 -- 5.3
   * Complete AsULearn Lesson *TBA*

## Day 18 (THU Jun 21)

   In Class:
   
   * Sampling distributions
      + calculation
      + simulation
      + approximation

   Before Next Class: 
   
   * Read *Chihara and Hesterberg* Section 4.3
   * TBA

## Day 19 (FRI Jun 22)

   In Class:
   
   * Central limit theorem
      + means
      + proportions
      + continuity correction

   Before Next Class: 
   
   * Read *Chihara and Hesterberg* Sections 5.1 -- 5.3 and 7.1 -- 7.4
   * TBA

## Day 20 (MON Jun 25)

   In Class:
   
   * One-sample bootstrap
   * Bootstrap standard error
   * Bootstrap percentile intervals

   Before Next Class: 
   
   * Read *Chihara and Hesterberg* Sections 5.4 -- 5.5
   * TBA

## Day 21 (TUE Jun 26)

   In Class:
   
   * Two-sample bootstrap
   * Comparing populations

   Before Next Class: 
   
   * Read *Chihara and Hesterberg* Sections 5.6 -- 5.9
   * TBA

## Day 22 (WED Jun 27)

   In Class:
   
   * Bias of an estimator
   * Bootstrap accuracy

   Before Next Class: 
   
   * Review *Chihara and Hesterberg* Chapters 4 and 5
   * TBA

## Day 23 (THU Jun 28)

   In Class:
   
   * Putting it all together!

   Before Next Class: 
   
   * Prepare for EXAM 3

## Day 24 (FRI Jun 29)

   In Class:
   
   * EXAM 3

<hr>

END!!!
