---
title: "Final Exam Review Topics"
author: "Fall 2019 // Jill E. Thomley"
date: '`r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`'
output: 
  html_document: 
    theme: yeti
    highlight: textmate
---

```{r globalopts, include = FALSE}
knitr::opts_chunk$set(comment = "", message = FALSE, warning = FALSE)
```

## Review Topics

### Descriptive Statistics

* Compare different groups using descriptive statistics
    + measures of center such as mean, median
    + measures of variability such as sd, IQR
* Interpret plots and determine distribution shape 
    + histogram
    + density plot
    + ecdf plot
* Interpret various assessments of normality
    + density plot
    + QQ plot
    + skewness
    + kurtosis
* Detect outliers using boxplots and fences

### Regression Modeling

* Interpret correlations / correlation matrices
* Interpret scatterplots (e.g., linearity, outliers)
* Interpret regression coefficients in context
* Interpret R^2^, residual standard error, MSE
* Discuss whether a model is a good predictor

### Central Limit Theorem

* Be able to explain sampling distributions and the CLT
* Explain whether the CLT applies in a given situation

### Bootstrapping

* Interpret the results of a bootstrap analysis
    + shape of the bootstrap sampling distribution
    + the meaning of a bootstrap percentile interval
* Explain whether bootstrapping is appropriate

### Hypothesis Testing

* Write the appropriate statistical hypotheses
* Determine the appropriate p-value in context
* Make the appropriate statistical decision about Ho
* Assess the shape of a permutation distribution
* Compare permutation and traditional results
* Explain whether a traditional test is valid in context
* Interpret hypothesis testing results in context
* Determine possibility of Type I or II errors

### Programming

* Be able to explain the function of a line or chunk of R code

## Final Exam

**Section 103 (class time TWR @ 12:30/01:00pm) — Your final exam is Tuesday, DEC 10 @ 11:00am in WA307B**<br>
**Section 104 (class time TWR @ 02:00pm) — Your final exam is Thursday, DEC 05 @ 02:00pm in WA307B**

1. I will give you up to 10 points of extra credit on the final exam if you prepare and submit a Markdown "cheat sheet" covering the above review topics.

2. You will not be asked to code on the final exam. I will provide analyses and code, and you will answer questions about them.

3. You will have the option to hand-write or type your answers to the final exam. Hand-written answers will be turned in to me, typewritten answers will be submitted online.

4. **As per the syllabus, you must pass the final exam with 60% *before* any extra credit to pass the class! No exceptions.**


***
### Go forth and study~!