---
title: "STT3850 Statistical Data Analysis 1<br>Fall 2019 Course Schedule"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
    highlight: textmate
    theme: cosmo
    css: "../css/style.css"
    keep_md: yes
---

***

```{block, updates, type='rmdimportant'}
* **This schedule is a work in progress. Check often for updates!**
* **MAJOR ASSESSMENTS / DUE DATES**
    * Project 1 --- SUN, SEP 22 @ 11pm
    * Project 2 --- SUN, OCT 13 @ 11pm
    * Project 3 --- TUE, NOV 26 @ 11pm
    * ~~Group Project --- WED, DEC 04 @ 11pm (Reading Day)~~ (REMOVED)
    * Final Exam for Section 103 --- TUE, DEC 10 @ 11am
    * Final Exam for Section 104 --- THU, DEC 05 @ 02pm
    * See schedule and AsULearn for DataCamp assessments.
* **Class meets on Tuesday, Wednesday, and Thursday, with exceptions noted.**
* **Most assignments are due on Sunday @ 11pm of the week in which they appear.** 
* **Refer to AsULearn for more detailed assignment instructions, rubrics, and grades.**
```

```{block, startnote, type='rmdnote'}
* We will use rental and free digital textbooks.
* All required software for this course is provided.
* Please bring a notebook and pencil to every class.
* Be prepared to actively participate and collaborate.
* Refer to the [Course Syllabus](../SyllabusSchedule/STT3850F19Syllabus.html) for additional details.
```


***
### Course Overview

STT3850 is a 3000-level introductory course with no statistics prerequisite, required for students from several majors who come into the course with a broad mix of mathematics, statistics, and programming skills. This means that the most effective mode of instruction tends to be a semi-flipped approach where some lecture occurs outside the classroom in the form of videos. This frees up class time to spend on collaborative work where students can give and receive help from peers and the instructor. Do not treat this instructional mode as an invitation to skip class! Your classmates are one of your greatest resources.

**Abbreviations**

MSRR = Mathematical Statistics with Resampling and R (rental textbook)  
MD = [Modern Dive](https://moderndive.com/) (digital textbook)  
DC = [DataCamp](https://www.datacamp.com/) (online tutorials)  


***
## Section 1: Programming

### Proficiencies

* Logical operators
* Vectors, matrices, lists
* `for` and `while` loops
* Writing basic functions
* Working in RStudio
* Using [R Markdown](https://rmarkdown.rstudio.com/)

### Explorations

* MSRR Chapter 1. Data and Case Studies
* MD [Chapter 1. Introduction](https://moderndive.com/index.html)
* MD [Chapter 2. Getting Started with Data in R](https://moderndive.com/2-getting-started.html)
* Video: [The History of S and R](https://youtu.be/jk9S3RTAl38) (~10 minutes)
* Video: [Introduction to the R Language](https://youtu.be/APm4SxJx0eg) (~30 minutes)
* [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)
* [Advanced `R` Style Guide](http://adv-r.had.co.nz/Style.html)
* [Initial Steps Toward Reproducible Research](https://kbroman.org/steps2rr/)
* [ASA Statement on the Role of Statistics in Data Science](http://magazine.amstat.org/blog/2015/10/01/asa-statement-on-the-role-of-statistics-in-data-science/)
* [A Tutorial on Using Functions in R!](https://www.datacamp.com/community/tutorials/functions-in-r-a-tutorial) <span style="color: red;">NEW!</span>
* [R Functions in Detail (With Examples)](https://www.datamentor.io/r-programming/function/) <span style="color: red;">NEW!</span>
* [Programming with R: Creating Functions](https://swcarpentry.github.io/r-novice-inflammation/02-func-R/) <span style="color: red;">NEW!</span>

### Week 01 (AUG 19)

#### In-Class Engagement

* Course introduction
* Technology accounts set-up
* Basics of the RStudio server 
* `R` scripts and R Markdown
* [YaRrr! Vectors](https://bookdown.org/ndphillips/YaRrr/vectors.html)
* [YaRrr! Creating matrices and dataframes](https://bookdown.org/ndphillips/YaRrr/creating-matrices-and-dataframes.html)

#### Integrations (Due SUN @ 11pm)

* [DataCamp](https://www.datacamp.com/) account 
* [RStudio server](https://mathr.math.appstate.edu) sign-in 
* Private Forum message 
* DC [Introduction to `R`](https://www.datacamp.com/courses/free-introduction-to-r)
* Introduction to R Feedback Survey

### Week 02 (AUG 26)

No class TUE, AUG 27 (Convocation)

#### In-Class Engagement

* `for` and `while`loops
* Writing basic functions
* More about `R` Markdown

#### Integrations (Due SUN @ 11pm)

* DC [Intermediate `R`](https://www.datacamp.com/courses/intermediate-r)
* Intermediate R Feedback Survey

***
## Section 2: Exploring (EDA)

### Proficiencies

* Frequency tables
* Summary statistics
* Graphs/visualizations 
    * barplots
    * histograms
    * densities
    * boxplots
* Assessing normality
* `tidyverse` tools

### Explorations

* MSRR Chapter 2. Exploratory Data Analysis
* MD [Chapter 3. Data Visualization](https://moderndive.com/3-viz.html)
* MD [Chapter 4. Data Wrangling](https://moderndive.com/4-wrangling.html)
* MD [Chapter 5. Data Importing & “Tidy” Data](https://moderndive.com/5-tidy.html)
* Slides: [Introduction to Datasets](https://stat-jet-asu.github.io/StatisticalDataAnalysis1/Slides/01_IntroToDatasets.html)
* Slides: [EDA---Categorical Data](https://stat-jet-asu.github.io/StatisticalDataAnalysis1/Slides/02_EDACategorical.html)
* Slides: [EDA---Numerical Data](https://stat-jet-asu.github.io/StatisticalDataAnalysis1/Slides/03_EDANumerical.html)
* Slides: [Normal Distribution](https://stat-jet-asu.github.io/StatisticalDataAnalysis1/Slides/04_NormalDistribution.html)
* Slides: [Assessing Normality](https://stat-jet-asu.github.io/StatisticalDataAnalysis1/Slides/05_NormalAssessment.html)
* Video: [Measures of Central Tendency](https://youtu.be/NM_iOLUwZFA) (~ 9 minutes)
* Video: [Measures of Variability](https://youtu.be/Cx2tGUze60s) (~ 12 minutes)
* Video: [The Sample Variance: Why Divide by n-1?](https://youtu.be/9ONRMymR2Eg) (~ 7 minutes)
* Video: [Proof that Sample Variance is Unbiased](https://youtu.be/D1hgiAla3KI) (~ 7 minutes)
* Video: [An Introduction to the Normal Distribution](https://youtu.be/iYiOVISWXS4) (~ 6 minutes)
* Video: [Standardizing Normally Distributed Random Variables](https://youtu.be/4R8xm19DmPM) (~ 11 minutes)
* Video: [Normal Quantile-Quantile Plot](https://youtu.be/X9_ISJ0YpGw) (~ 12 minutes)
* [GGPlot Examples Best Reference](https://www.datanovia.com/en/blog/ggplot-examples-best-reference/)
* [`ggplot2` reference page](https://ggplot2.tidyverse.org/reference/index.html)
* [`dplyr` reference page](https://dplyr.tidyverse.org/reference/index.html)
* [`tidyr` reference page](https://tidyr.tidyverse.org/reference/index.html)

### Week 03 (SEP 02)

#### In-Class Engagement

* [introduction to `dplyr`](http://stat545.com/block009_dplyr-intro.html)
* [`dplyr` functions for a single dataset](http://stat545.com/block010_dplyr-end-single-table.html)
* [Introduction to `ggplot2`](https://uc-r.github.io/ggplot_intro)

#### Integrations (Due SUN @ 11pm)

* DC [Introduction to Data](https://www.datacamp.com/courses/introduction-to-data)
* Introduction to Data Feedback Survey
* DC [Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse)
* Introduction to the Tidyverse Feedback Survey

### Week 04 (SEP 09)

#### In-Class Engagement

* [How to Change GGPlot Labels](https://www.datanovia.com/en/blog/how-to-change-ggplot-labels/)
* Boxplots and detecting outliers in data
* Normal distribution and assessing normality

#### Integrations (Due SUN @ 11pm)

* DC [Data Visualization with `ggplot2` (Part 1)](https://www.datacamp.com/courses/data-visualization-with-ggplot2-1)
* Data Visualization with `ggplot2` (Part 1) Feedback Survey
* DC [Exploratory Data Analysis](https://www.datacamp.com/courses/exploratory-data-analysis)
* Exploratory Data Analysis Feedback Survey

### Week 05 (SEP 16)

#### In-Class Engagement

* Work on Project 1

#### Integrations (Due SUN @ 11pm)

* Project 1 write-up


***
## Section 3: Modeling

### Proficiencies

* Scatterplots
* Pearson correlation
* Simple linear models
* Parallel slopes model
* Model interpretation
    * R^2^
    * MSE and RSME
    * Slope / intercept
* Predicting with models
* `moderndive` tools

### Explorations

* MD [Chapter 6. Basic Regression](https://moderndive.com/6-regression.html)
* MD [Chapter 7. Multiple Regression](https://moderndive.com/7-multiple-regression.html)
* Slides: [Introduction to Datasets](https://stat-jet-asu.github.io/StatisticalDataAnalysis1/Slides/01_IntroToDatasets.html)
* Video: [Introduction to Simple Linear Regression](https://youtu.be/KsVBBJRb9TE) (~ 8 minutes)
* Video: [The Least Squares Regression Line](https://youtu.be/coQAAN4eY5s)(~ 8 minutes)
* Video: [Interpreting Model Parameters](https://youtu.be/I8Dr1OGUdZQ) (~ 5 minutes)
* Video: [Simple Linear Regression: An Example](https://youtu.be/xIDjj6ZyFuw) (~ 10 minutes)
* Video: [Always Plot Your Data!](https://youtu.be/sfH43temzQY) (~ 6 minutes)
* Video: [Leverage and Influential Points](https://youtu.be/xc_X9GFVuVU) (~ 7 minutes)
* [`moderndive` package documentation](https://cran.r-project.org/web/packages/moderndive/moderndive.pdf) (pp. 7-11)
* [GGPLot Scatter Plot](https://www.datanovia.com/en/lessons/ggplot-scatter-plot/)

### Week 06 (SEP 23)

#### In-Class Engagement

* Scatterplots in `ggplot2`
* Correlation coefficients
* Least squares criterion
* Model fitting with `lm`

#### Integrations (Due SUN @ 11pm)

* DC [Modeling with Data in the Tidyverse](https://www.datacamp.com/courses/modeling-with-data-in-the-tidyverse)
* Modeling with Data in the Tidyverse Feedback Survey

### Week 07 (SEP 30)

#### In-Class Engagement

* Parallel slopes model
* Making predictions
* Influential points

#### Integrations (Due SUN @ 11pm)

* Make sure you are all caught up on material!

### Week 08 (OCT 07)

OCT 08 is the halfway point!

#### In-Class Engagement

* Work on Project 2

#### Integrations (Due SUN @ 11pm)

* Project 2 write-up


***
## Section 4: Sampling

### Proficiencies

* Sampling from vectors and datasets
* Sampling with/without replacement
* Sampling distributions using simulation
* Explaining/using the Central Limit Theorem
* Constructing and using confidence intervals

### Explorations

* MSRR Chapter 4. Sampling Distributions
* MSRR Chapter 5. Introduction to Confidence Intervals
* MSRR Chapter 7. More Confidence Intervals
* MD [Chapter 7. Sampling](https://moderndive.com/7-sampling.html)
* MD [Chapter 8. Bootstrapping and Confidence Intervals](https://moderndive.com/8-confidence-intervals.html)
* Video: [Sampling Distributions: Introduction to the Concept](https://youtu.be/Zbw-YvELsaM) (~ 8 minutes)
* Video: [The Sampling Distribution of the Sample Mean](https://youtu.be/q50GpTdFYyI) (~ 12 minutes)
* Video: [Introduction to the Central Limit Theorem](https://youtu.be/Pujol1yC1_A) (~ 13 minutes)
* Video: [Introduction to Confidence Intervals](https://youtu.be/27iSnzss2wM) (~ 7 minutes)
* Video: [Introduction to the t Distribution](https://youtu.be/Uv6nGIgZMVw) (~ 9 minutes)

### Week 09 (OCT 14)

No class TUE, OCT 15 (Fall Break)

#### In-Class Engagement

* Sampling in `R` with and without replacement
* Fundamentals of the Central Limit Theorem (CLT)

#### Integrations (Due SUN @ 11pm)

* DC [Foundations of Probability in R](https://www.datacamp.com/courses/foundations-of-probability-in-r)

### Week 10 (OCT 21)

#### In-Class Engagement

* Bootstrap percentile intervals
* CLT-based confidence intervals

#### Integrations (Due SUN @ 11pm)

* DC [Foundations of Inference](https://www.datacamp.com/courses/foundations-of-inference)

### Week 11 (OCT 28)

#### In-Class Engagement

* Bootstrap percentile intervals
* CLT-based confidence intervals

#### Integrations (Due SUN @ 11pm)

* DC [Inference for Numerical Data](https://www.datacamp.com/courses/inference-for-numerical-data)

***
## Section 5: Inferring

### Explorations

* Read MSRR Chapter 3. Introduction to Hypothesis Testing
* Read MSRR Chapter 8. More Hypothesis Testing
* Read MSRR Chapter 10. (Testing for) Categorical Data
* MD [Chapter 8. Bootstrapping & Confidence Intervals](https://moderndive.com/8-confidence-intervals.html)
* MD [Chapter 9. Hypothesis Testing](https://moderndive.com/9-hypothesis-testing.html)
* Video: [An Introduction to Hypothesis Testing](https://youtu.be/tTeMYuS87oU) (~ 10 minutes)
* Video: [What is a p-value?](https://youtu.be/UsU-O2Z1rAs) (~ 11 minutes)
* Video: [Type I Errors, Type II Errors, and the Power of the Test](https://youtu.be/7mE-K_w1v90) (~ 8 minutes)
* Video: [Inference for Two Means: Introduction](https://youtu.be/86ss6qOTfts) (~ 6 minutes)
* Video: [The Sampling Distribution of the Difference in Sample Means](https://youtu.be/4HB-FL529ag) (~ 6 minutes)

### Week 12 (NOV 04)

#### In-Class Engagement

* Hypothesis testing

### Week 13 (NOV 11)

#### In-Class Engagement

* Hypothesis testing


### Week 14 (NOV 18)

#### In-Class Engagement

* Hypothesis testing (TUE)
* Work on Project 3 (WED, THU)

### Week 15 (NOV 25)

#### In-Class Engagement

* Work on Project 3
* No class WED, NOV 27 (Thanksgiving)  
* No class THU, NOV 28 (Thanksgiving)

#### Integrations (Due TUE @ 11pm)

* Project 3 write-up

### Week 16 (DEC 02)

#### In-Class Engagement

* Review for Final Exam
* Last class day is TUE, DEC 03  
* Reading Day is WED, DEC 04 


***
## Final Exam

```{block, final, type='rmdnote'}
* Final Exam for Section 103 (TWR @ 12:30pm) --- TUE, DEC 10 @ 11am
* Final Exam for Section 104 (TWR @ 02:00pm) --- THU, DEC 05 @ 02pm
* [ASU Fall 2019 Exam Schedule](https://registrar.appstate.edu/sites/registrar.appstate.edu/files/asu_fall_2019_exam_schedule.pdf)
```

