---
title: "STT3850 Statistical Data Analysis 1<br>Fall 2019 Course Schedule"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    toc: false
    toc_depth: 4
    toc_float: true
    highlight: textmate
    theme: cosmo
    css: "../css/style.css"
    keep_md: yes
---

***

```{block, updates, type='rmdimportant'}
* **This schedule is a work in progress. Check often for updates!**
```

```{block, startnote, type='rmdnote'}
* We will use rental and free digital textbooks.
* All required software for this course is provided.
* Please bring a notebook and pencil to every class.
* Be prepared to actively participate and collaborate.
* Refer to the [Course Syllabus](../SyllabusSchedule/STT3850F19Syllabus.html) for additional details.
```


***
### Course Overview

STT3850 is a 3000-level introductory course with no statistics prerequisite, required for students from several majors who come into the course with a broad mix of mathematics, statistics, and programming skills. This means that the most effective mode of instruction tends to be a semi-flipped approach where some lecture occurs outside the classroom in the form of videos. This frees up class time to spend on collaborative work where students can give and receive help from peers and the instructor. Do not treat this instructional mode as an invitation to skip class! Your classmates are one of your greatest resources.

**Abbreviations**

MSRR = Mathematical Statistics with Resampling and R (rental textbook)  
MD = [Modern Dive](https://moderndive.com/) (digital textbook)  
DC = [DataCamp](https://www.datacamp.com/) (online tutorials)  
JB = [JB Statistics](https://www.youtube.com/user/jbstatistics/videos) (videos)  
HW = homework assignment

```{block, duedates, type='rmdimportant'}
* **Class meets on Tuesday, Wednesday, and Thursday, with exceptions noted.**
* **Most assignments are due on Sunday @ 11pm of the week in which they appear.** 
* **Refer to AsULearn for more detailed assignment instructions, rubrics, and grades.**
```


***
## Section 1: Programming

### Proficiencies

* Logical operators
* Vectors, matrices, lists
* `for` and `while` loops
* Writing basic functions

### Explorations

* MSRR Chapter 1. Data and Case Studies
* MD [Chapter 1. Introduction](https://moderndive.com/index.html)
* MD [Chapter 2. Getting Started with Data in R](https://moderndive.com/2-getting-started.html)
* [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)
* [Initial Steps Toward Reproducible Research](https://kbroman.org/steps2rr/)
* [ASA Statement on the Role of Statistics in Data Science](http://magazine.amstat.org/blog/2015/10/01/asa-statement-on-the-role-of-statistics-in-data-science/)
* Video: [The History of S and R](https://youtu.be/jk9S3RTAl38) (~10 minutes)
* Video: [Introduction to the R Language](https://youtu.be/APm4SxJx0eg) (~30 minutes)

### Week 01 (AUG 19)

#### Integrations (Due SUN @ 11pm)

* [DataCamp](https://www.datacamp.com/) account 
* [RStudio server](https://mathr.math.appstate.edu) sign-in 
* Private Forum message 
* DC [Introduction to `R`](https://www.datacamp.com/courses/free-introduction-to-r)
* Reflection #01

#### Class Activities

* Course introduction
* Technology accounts set-up
* Basics of the RStudio server 
* `R` scripts and R Markdown
* Basics of creating `R` vectors 

### Week 02 (AUG 26)

No class TUE, AUG 27 (Convocation)

#### Integrations (Due SUN @ 11pm)

* DC [Intermediate `R`](https://www.datacamp.com/courses/intermediate-r)
* Reflection #02

#### Class Activities

* `for` and `while`loops
* Writing basic functions
* More about R Markdown


***
## Section 2: Exploring (EDA)

### Proficiencies

* Frequency tables
* Summary statistics
* Graphs/visualizations 
    * barplots
    * histograms
    * densities
    * boxplots
* Assessing normality

### Explorations

* MSRR Chapter 2. Exploratory Data Analysis
* MD [Chapter 3. Data Visualization](https://moderndive.com/3-viz.html)
* MD [Chapter 4. Data Wrangling](https://moderndive.com/4-wrangling.html)
* MD [Chapter 5. Data Importing & “Tidy” Data](https://moderndive.com/5-tidy.html)
* [GGPlot Examples Best Reference](https://www.datanovia.com/en/blog/ggplot-examples-best-reference/)
* [`ggplot2` reference page](https://ggplot2.tidyverse.org/reference/index.html)
* [`dplyr` reference page](https://dplyr.tidyverse.org/reference/index.html)
* [`tidyr` reference page](https://tidyr.tidyverse.org/reference/index.html)

### Week 03 (SEP 02)

#### Integrations (Due SUN @ 11pm)

* DC [Introduction to Data](https://www.datacamp.com/courses/introduction-to-data)
* DC [Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse)
* Reflection #03

#### Class Activities

* [introduction to `dplyr`](http://stat545.com/block009_dplyr-intro.html)
* [`dplyr` functions for a single dataset](http://stat545.com/block010_dplyr-end-single-table.html)

### Week 04 (SEP 09)

#### Integrations (Due SUN @ 11pm)

* DC [Data Visualization with `ggplot2` (Part 1)](https://www.datacamp.com/courses/data-visualization-with-ggplot2-1)
* DC [Exploratory Data Analysis](https://www.datacamp.com/courses/exploratory-data-analysis)
* Reflection #04

#### Class Activities

* [Introduction to `ggplot2`](https://uc-r.github.io/ggplot_intro)
* Boxplots in `ggplot2`
* [How to Change GGPlot Labels: Title, Axis and Legend](https://www.datanovia.com/en/blog/how-to-change-ggplot-labels/)

```{block, week04note, type='rmdnote'}
* The [`tidyverse`](https://www.tidyverse.org/) is "an opinionated collection of R packages designed for data science" that share a common philosophy for effective data manipulation, explorations and visualization. We will use it througout this course.
* Check out [RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/) for data transformation, data visualization, and Markdown.
```


*** 
## Assessment #1

### Week 05 (SEP 16)

#### Integrations (Due SUN @ 11pm)

* Project 1
* Reflection #05

#### Class Activities

* Work on Project 1


***
## Section 3: Modeling

### Proficiencies

* Correlation
* Scatterplots
* Linear models 
* Model interpretation
* Predicting with models

### Explorations

* MD [Chapter 6. Basic Regression](https://moderndive.com/6-regression.html)
* MD [Chapter 7. Multiple Regression](https://moderndive.com/7-multiple-regression.html)
* [`moderndive` package documentation](https://cran.r-project.org/web/packages/moderndive/moderndive.pdf) (pp. 7-11)
* [GGPLot Scatter Plot](https://www.datanovia.com/en/lessons/ggplot-scatter-plot/)

### Week 06 (SEP 23)

#### Integrations (Due SUN @ 11pm)

* DC [Modeling with Data in the Tidyverse](https://www.datacamp.com/courses/modeling-with-data-in-the-tidyverse)
* Reflection #06

#### Class Activities

* TBA

### Week 07 (SEP 30)

#### Integrations (Due SUN @ 11pm)

* Reflection #07

#### Class Activities

* TBA


***
## Assessment 2

### Week 08 (OCT 07)

OCT 08 is the halfway point!

#### Integrations (Due SUN @ 11pm)

* Project 2
* Reflection #10

#### Class Activities

* Work on Project 2


***
## Section 4: Sampling

### Proficiencies

* Sampling from vectors and datasets
* Sampling with / without replacement

### Explorations

* MSRR Chapter 4. Sampling Distributions
* MSRR Chapter 5. Introduction to Confidence Intervals
* MSRR Chapter 7. More Confidence Intervals
* MD [Chapter 8. Sampling](https://moderndive.com/8-sampling.html)
* MD [Chapter 9. Bootstrapping and Confidence Intervals](https://moderndive.com/9-confidence-intervals.html)

### Week 09 (OCT 14)

No class TUE, OCT 15 (Fall Break)

#### Integrations (Due SUN @ 11pm)

* DC [Foundations of Probability in R](https://www.datacamp.com/courses/foundations-of-probability-in-r)
* Reflection #08

#### Class Activities

* TBA

### Week 10 (OCT 21)

#### Integrations (Due SUN @ 11pm)

* DC [Foundations of Inference](https://www.datacamp.com/courses/foundations-of-inference)
* Reflection #09

#### Class Activities

* TBA


***
## Section 5: Inferring

### Explorations

* Read MSRR Chapter 3. Introduction to Hypothesis Testing
* Read MSRR Chapter 8. More Hypothesis Testing
* Read MSRR Chapter 10. (Testing for) Categorical Data

### Week 11 (OCT 28)

#### Integrations (Due SUN @ 11pm)

* DC [Inference for Numerical Data](https://www.datacamp.com/courses/inference-for-numerical-data)
* Reflection #11

#### Class Activities

* TBA

#### Prepare for Next Week

* TBA


### Week 12 (NOV 04)

#### Integrations (Due SUN @ 11pm)

* DC [Inference for Categorical Data](https://www.datacamp.com/courses/inference-for-categorical-data)
* Reflection #12

#### Class Activities

* TBA

#### Prepare for Next Week

* TBA


### Week 13 (NOV 11)

#### Integrations (Due SUN @ 11pm)

* TBA
* Reflection #13

#### Class Activities

* TBA

#### Prepare for Next Week

* TBA

***
## Assessment #3

### Week 14 (NOV 18)

#### Integrations (Due SUN @ 11pm)

* Individual Project 3
* Reflection #14

#### Class Activities

* Work on Project 3

***
## Assessment #4

### Week 15 (NOV 25)

No class WED, NOV 27 (Thanksgiving)  
No class THU, NOV 28 (Thanksgiving)

#### Integrations (Due SUN @ 11pm)

* No assignment due

#### Class Activities

* Work on Group Project

### Week 16 (DEC 02)

Last day of class is TUE, DEC 03  
Reading Day is WED, DEC 04  

#### Due Wednesday @ 11pm

* Group Project write-up
* Reflection #15

#### Class Activities

* Work on Group Project

#### Prepare for Next Week

* Prepare your cheat sheet
* Study for your final exam

***
## Final Exam

```{block, final, type='rmdnote'}
* Our [final exam times](https://registrar.appstate.edu/sites/registrar.appstate.edu/files/asu_spring_2019_exam_schedule.pdf) are XXXX @ XX:XXxx in our usual classroom. You will present your projects and complete XXX at this time.
```
