---
title: "Digital Communication, Part 1"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    highlight: textmate
    theme: cosmo
---

<hr>

### The Process

A [digital communication channel transmits binary signals](http://what-when-how.com/data-communications-and-networking/digital-transmission-of-digital-data/) (0 or 1). Suppose a particular system is susceptible to electronic interference, so there is a 1% chance that any bit sent by the system will be incorrectly received (i.e., a sent 0 is mistakenly interpreted as 1). Assume that the interference is non-patterned, so all bit transmission errors are random and independent. One simple method for error reduction is repetition code. For critical messages, we can use triple repetition code (TRC). The individual digits are transmitted as repeated blocks of three identical digits (a single 0 in the message would be sent as the block 000 and a single 1 would be sent as 111). The receiver uses a "majority logic decoding" method on blocks. If the majority of the three-block's digits are interpreted by the receiver as 0, then the transmitted digit represented by the block is recorded as a single 0. If the majority are interpreted as 1, then the transmitted digit is recorded as a 1.


### The Problem

How can we model this system? What are its performance characteristics? How many errors can we expect if we transmit them using this system? Can we modify the system for better performance?


### Your Analyses

1) A 1000 Mbit/s system transmits 10^9^ bits per second. If each bit has a 1% chance of being incorrectly received, how many errors per second would we expect to get? What is the standard deviation in the number of errors?

2) Let X be the number of bits in a single TRC block correctly received. Compute the pmf of X. Display the results in a tibble and a plot. Color the bars corresponding to "majority" red. What is the probability that any single TRC block (e.g., 000) is interpreted correctly?

3) Suppose we have a parallel system that lets us transmit 10^9^ bits per second using TRC. How many errors per second would we expect to get? What percentage reduction does this represent compared to the single-bit system?

4) In the ASCII representation of the alphabet, each letter is coded using a permutation of eight 0’s and 1’s. For example, J = 01001010. If we transmit a letter using the TRC system, what is the probability the letter will be interpreted correctly?

5) Modify the code below to display the ASCII representation of the last name of each member of your group. What is the probability that each name would be correctly interpreted at the receiving end (i.e., there are no mistakes in any letter)?

```{r, eval=FALSE}
require(gtools)
require(broman)
require(BMS)
NAMELET  <- c("T", "h", "o", "m", "l", "e", "y")
n        <- length(NAMELET)
NAMEHEX  <- convert2hex(asc(NAMELET))
NAMEBIN  <- matrix(rep(0,n*8),ncol=8)
for (i in 1:n) {
    NAMEBIN[i,1:8] <- hex2bin(NAMEHEX[i])
}
rownames(NAMEBIN) <- NAMELET
colnames(NAMEBIN) <- c("Bit1","Bit2","Bit3","Bit4","Bit5","Bit6","Bit7","Bit8")
print(NAMEBIN)
```

6) We plan to transmit the 1,444 characters of Lincoln's Gettysburg Address (Bliss version), which includes letters, spaces between words, and punctuation. A space or punctuation is treated exactly like a letter; e.g., the code for a space is 00100000. How many character errors should we expect to get? What is the standard deviation in the number of errors?

<hr>

END PART 1