---
title: "Digital Communication, Part 2"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    highlight: textmate
    theme: cosmo
---

<hr>

### The Process

A [digital communication channel transmits binary signals](http://what-when-how.com/data-communications-and-networking/digital-transmission-of-digital-data/) (0 or 1). Suppose a particular system is susceptible to electronic interference, so there is a 1% chance that any bit sent by the system will be incorrectly received (i.e., a sent 0 is mistakenly interpreted as 1). Assume that the interference is non-patterned, so all bit transmission errors are random and independent. One simple method for error reduction is repetition code. For critical messages, we can use triple repetition code (TRC). The individual digits are transmitted as repeated blocks of three identical digits (a single 0 in the message would be sent as the block 000 and a single 1 would be sent as 111). The receiver uses a "majority logic decoding" method on blocks. If the majority of the three-block's digits are interpreted by the receiver as 0, then the transmitted digit represented by the block is recorded as a single 0. If the majority are interpreted as 1, then the transmitted digit is recorded as a 1.


### The Problem

How can we model this system? What are its performance characteristics? How many errors can we expect if we transmit them using this system? Can we modify the system for better performance?


### Your Analyses

1) In Part 1, you analyzed error rates for a single-channel system and a TRC system. One way to reduce transmission errors in either system would be to improve the initial 1% error rate. How much would reducing the error rate improve the performance of the TRC system? Create a plot that shows error rates from 0% to 1% (in increments of 0.1) on the x-axis versus the corresponding probability that any single TRC block (e.g., 000) is interpreted correctly (y-axis). To what value do we have to reduce the initial error rate in order for the probability of a block being correctly transmitted to be at least 99.99%?

2) A 1000 Mbit/s system transmits 10^9^ bits per second. Each bit has a 0.03% chance of being incorrectly received when we use TRC and all bits are independent. There are are 86,400 seconds in a day. If X is the number of incorrect bits in a single second, use `rbinom` to simulate the distribution of X for a single day. Assess your simulation results for normality using a density plot, ECDF plot, QQ plot, and goodness of fit test. What do you conclude?

<hr>

END PART 2