---
title: "Popularity Study, Part 2"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    highlight: textmate
    theme: cosmo
---

<hr>

### The Process

In 1992, researchers Melissa A. Chase and Gail M. Dummer of Michigan State University collected data from a sample of 4th, 5th, and 6th grade students who were enrolled in schools in Ingham and Clinton counties in order to study the role certain factors play in determining social status. They selected a stratified random sample from urban, suburban, and rural school districts, with the goal of having about 1/3 of the students come from each district type. The dataset contains some data from this study. ([data](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/popular.csv)) || ([description](https://stat-jet-asu.github.io/Datasets/InstructorDescriptions/popular.html))


### The Problem

What were the kids' self-selected goals in school? Do they differ according to other important variables? For this part of the project, you will use inferential analysis to answer these questions. 


### Your Analyses

For all tests, write the null and alternative hypotheses, report the test statistic and the p-value, state whether or not you reject the null hypothesis, and then give your conclusion in terms of the original question.

1) Researchers chose their sample with the goal of having about 1/3 of  students come from each school district type. Were they successful? Perform a goodness of fit test. If they weren't successful, which districts have too many or two few students selected?

2) Perform a permutation hypothesis test to determine whether there is there a statistically significant relationship between gender and top goal. If so, what is the nature of the relationship?

3) Given the sampling strategy the researchers used in this study, we could consider each type of school district to be a separate population. Perform a traditional hypothesis test to determine whether the distribution of top goal is the same in all three types of school district. If not, in what ways do the district types differ?

4) A chi-square test shows that the three types of school districts do not have the same proportions of boys and girls (p = 0.0024). How might this affect your tests and conclusions in (2) and (3)?

<hr>

END PART 2

