---
title: "Popularity Study, Part 1"
author: "Instructor: Jill E. Thomley (thomleyje@appstate.edu)"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: 
  html_document: 
    highlight: textmate
    theme: cosmo
---

<hr>

### The Process

In 1992, researchers Melissa A. Chase and Gail M. Dummer of Michigan State University collected data from a sample of 4th, 5th, and 6th grade students who were enrolled in schools in Ingham and Clinton counties in order to study the role certain factors play in determining social status. They selected a stratified random sample from urban, suburban, and rural school districts, with the goal of having about 1/3 of the students come from each district type. The dataset contains some data from this study. ([data](https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/popular.csv)) || ([description](https://stat-jet-asu.github.io/Datasets/InstructorDescriptions/popular.html))


### The Problem

What were the kids' self-selected goals in school? Do they differ according to other important variables? For this part of the project, you will use exploratory data analysis to answer these questions. 


### Your Analyses

1) Display the dataset structure and a basic `summary()`.

2) Create a table and a plot that divides each goal according to the percentage of boys and girls who chose that goal. Does choice of top goal appear to be related to gender? Explain.

3) Create a table and a plot that divides each district type according to the percentage of students who chose each goal. Does choice of top goal appear to be related to district type? Explain.

4) Create four barplots to compare the ranks given to grades, sports, looks, and money by boys and girls. Use unstacked bars in these plots. Do the rankings appear to differ by gender? Explain.

5) Are there any unusually young or old students in this sample? Compute the fences to determine what qualifies as unusually young or old. Use them to filter the dataset and print only those cases.

<hr>

END PART 1

