---
title: "Exam 02 Summary"
author: "Instructor: Dr. Jill E. Thomley"
date: "Updated: `r Sys.time()`"
output:
  html_document:
    theme: cosmo
---

<hr>

```{r, echo=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(ggthemes)
gradesraw <- read.csv("exam02scores.csv")
grades <- filter(gradesraw, Exam2 > 0)
```


```{r, echo=FALSE}
ggplot(grades, aes(x=1, y=Exam2)) + 
  geom_boxplot() +
  coord_flip() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  ggtitle("Scores on Exam 2") +
  xlab("") +
  ylab("Total Score") +
  scale_y_continuous(limits = c(0, 100))

grades %>% summarize(n = n(),
                     Mean  = round(mean(Exam2),1),
                     StDev = round(sd(Exam2),1),
                     Min   = round(fivenum(Exam2)[1],1),
                     Q1    = round(fivenum(Exam2)[2],1),
                     Med   = round(fivenum(Exam2)[3],1),
                     Q3    = round(fivenum(Exam2)[4],1),
                     Max   = round(fivenum(Exam2)[5],1),
                     IQR   = round(IQR(Exam2), 2),
                     Range = round(diff(range(Exam2))))
```

