---
title: "Comparing Two Proportions: Pigeons Example"
author: "Author: Jill E. Thomley"
date: 'Updated: `r format(Sys.time(), "%A, %B %d, %Y @ %X")`'
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(comment="", message=FALSE, warning=FALSE)
library(tidyverse)
```


### Load the Dataset

```{r}
homing <- read.csv("https://raw.githubusercontent.com/STAT-JET-ASU/Datasets/master/Instructor/homingpigeons.csv")
str(homing)
```


### Explore the Data

```{r}
summaries <- homing %>% 
  group_by(group) %>% summarize(n = n(), 
                                phat_y = mean(home == "no"), 
                                phat_n = mean(home == "yes"))
print.data.frame(summaries, rwo.names = FALSE)

ggplot(homing, aes(x = group, fill = home)) + geom_bar(position = "fill") + ylab("proportion")

ggplot(summaries, aes(x = group, y = phat_n)) + 
  geom_bar(stat = "identity") + 
  ggtitle("Proportion of No")

ggplot(summaries, aes(x = group, y = phat_y)) + 
  geom_bar(stat = "identity") + 
  ggtitle("Proportion of Yes")

summaries$n * summaries$phat_y >= 15
summaries$n * summaries$phat_n >= 15
```


### The Traditional Test

```{r}
table(homing$group, homing$home)

obsPropDiff_n <- -diff(summaries$phat_n)
obsPropDiff_y <- -diff(summaries$phat_y)
print(obsPropDiff_n)
print(obsPropDiff_y)

homeTest1 <- prop.test(table(homing$group, homing$home), correct = FALSE)
print(homeTest1)

homeTest2 <- prop.test(table(homing$group, homing$home), correct = TRUE)
print(homeTest2)
```


### Permutation Resampling Test

```{r}
N <- 10^5 - 1
permPropDiff <- numeric(N)

testdata <- homing$home

for (i in 1:N){
   index <- sample(77, 38)
   control <- testdata[index]
   magnet  <- testdata[-index]
   permPropDiff[i] <- mean(control == "yes") - mean(magnet == "yes")
}

ggplot(NULL, aes(x = permPropDiff)) + 
  geom_histogram(bins = 30, fill = "lightblue") + 
  geom_vline(xintercept = obsPropDiff_y, color = "red") +
  labs(title = "Resampling Mean Differences")

# lower tail test with Ha: mu_b < mu_g

pvalue.lower <- (sum(permPropDiff <= obsPropDiff_y) + 1) / (N + 1)

# upper tail test with Ha: mu_b > mu_g

pvalue.upper <- (sum(permPropDiff >= obsPropDiff_y) + 1) / (N + 1)

# two-tail test with Ha: mu_b =/= mu_g

pvalue.twotail <- 2 * min(pvalue.lower, pvalue.upper)

data.frame(alternative = c("Lower-Tail", "Upper-Tail", "Two-Tailed"),
           pvalue      = c(pvalue.lower, pvalue.upper, pvalue.twotail))
```

