---
title: "Course Descriptions for Depth Assignment #1"
author: "Created by Jill E. Thomley"
date: '`r format(Sys.time(), "%A, %B %d, %Y @ %I:%M %p")`'
output: 
  html_document: 
    theme: cosmo
    highlight: textmate
---

```{r globaloptions, include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = NA)
```

<hr>

### **Data Manipulation with dplyr**

#### **Prerequisite**

Introduction to the Tidyverse

#### **Course Description**

Say you've found a great dataset and would like to learn more about it. How can you start to answer the questions you have about the data? You can use dplyr to answer those questions—it can also help with basic transformations of your data. You'll also learn to aggregate your data and add, remove, or change the variables. Along the way, you'll explore a dataset containing information about counties in the United States. You'll finish the course by applying these tools to the babynames dataset to explore trends of baby names in the United States. ([**explore more about this course**](https://learn.datacamp.com/courses/data-manipulation-with-dplyr))


### **Introduction to Data Visualization with ggplot2**

#### **Prerequisite**

Introduction to the Tidyverse

#### **Course Description**

The ability to produce meaningful and beautiful data visualizations is an essential part of your skill set as a data scientist. This course, the first R data visualization tutorial in the series, introduces you to the principles of good visualizations and the grammar of graphics plotting concepts implemented in the ggplot2 package. ggplot2 has become the go-to tool for flexible and professional plots in R. Here, we’ll examine the first three essential layers for making a plot - Data, Aesthetics and Geometries. By the end of the course you will be able to make complex exploratory plots. ([**explore more about this course**](https://learn.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2))


### **Interactive Data Visualization with plotly in R**

#### **Prerequisite**

Introduction to the Tidyverse

#### **Course Description**

Interactive graphics allow you to manipulate plotted data to gain further insight. As an example, an interactive graphic would allow you to zoom in on a subset of your data without the need to create a new plot. In this course, you will learn how to create and customize interactive graphics in plotly using the R programming language. Along the way, you will review data visualization best practices and be introduced to new plot types such as scatterplot matrices and binned scatterplots. ([**explore more about this course**](https://learn.datacamp.com/courses/interactive-data-visualization-with-plotly-in-r))


### **Visualizing Big Data with Trelliscope in R**

#### **Prerequisite**

Introduction to the Tidyverse

#### **Course Description**

Having honed your visualization skills by learning ggplot2, it's now time to tackle larger datasets. In this course, you will learn several techniques for visualizing big data, with particular focus on the scalable visualization technique of faceting. You will learn how to put this technique into action using the Trelliscope approach as implemented in the trelliscopejs R package. Trelliscope plugs seamlessly into standard R workflows and produces interactive visualizations that allow you to visually explore your data in detail. By the end of this course, you will be able to easily create interactive exploratory displays of large datasets that will help you and your colleagues gain new insights into your data. ([**explore more about this course**](https://learn.datacamp.com/courses/visualizing-big-data-with-trelliscope-in-r))


### **Interactive Maps with leaflet in R**

#### **Prerequisite**

Introduction to the Tidyverse

#### **Course Description**

Get ready to have some fun with maps! Interactive Maps with leaflet in R will give you the tools to make attractive and interactive web maps using spatial data and the tidyverse. In this course, you will create maps using the IPEDS dataset, which contains data on U.S. colleges and universities. Along the way, you will customize our maps using labels, popups, and custom markers, and add layers to enhance interactivity. Following the course, you will be able to create and customize your own interactive web maps to reveal patterns in your data. ([**explore more about this course**](https://learn.datacamp.com/courses/interactive-maps-with-leaflet-in-r))

<hr>