---
title: "Q&A: Semmelweis and Handwashing #1"
author: "<br>NAME:"
output:
  html_document:
    highlight: textmate
    theme: yeti
---

<hr>
### Answer the following questions your own...

#### **Identifying the Problem**

Based on the annual mortality data from 1841-1846, do you think Dr. Semmelweis was right to believe that there was a problem in Clinic 1 versus Clinic 2? Support your answer using specific information from the problem description and analysis.

<br><br><br><br><br><br><br><br><br><br><br><br><br>

#### **Semmelweis's Intervention**

Does the monthly mortality data from before and after Semmelweis's handwashing intervention generally support his theory that clean hands reduce infection? Support your answer using specific information from the problem description and analysis.

<br><br><br><br><br><br><br><br><br><br><br><br><br>

### Discuss in pairs or groups and then answer...

#### **Pooling Your Knowledge**

Would you make any changes to your previous answers after comparing and discussing them with classmates? Why or why not?

<br><br><br><br><br><br><br><br><br><br><br><br><br>

Could the differences observeed between the two clinics or before and after handwashing be just coincidences? Are they *likely* to be coincidences? Why or why not?